# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "https://sunshinecommittee.github.io" # the base hostname & protocol for your site
title: "Sunshine Committee"
email: devs@sunshinecommittee.io
description: >- # this means to ignore newlines until "baseurl:"
  Unique digital experiences
twitter_username: sunshineDevs
github_username:  SunshineCommittee

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-redirect-from
exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
permalink: :title
collections: 
  galleries:
    output: true
  contacts:
    output: true
  games:
    output: true
  articles: 
    output: true
  posts: 
    output: true
    
defaults:
  - 
    scope:
      path: ""
      type: "galleries"
    values:
      layout: "gallery"
  - 
    scope:
      path: ""
      type: "contacts"
    values:
      layout: "contact"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - 
    scope:
      path: ""
      type: "games"
    values:
      layout: "game"
  -
    scope:
      path: ""
      type: "articles"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post-redirect"


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
